CREATE TABLE posts (
    no              INTEGER PRIMARY KEY NOT NULL,
    resto           INTEGER NOT NULL,
    sticky          INTEGER NOT NULL,
    closed          INTEGER NOT NULL,
    now             TEXT NOT NULL,
    time            INTEGER NOT NULL,
    name            TEXT NOT NULL,
    trip            TEXT NULL,
    id              TEXT NULL,
    capcode         TEXT NULL,
    country         TEXT NULL,
    country_name    TEXT NULL,
    board_flag      TEXT NULL,
    flag_name       TEXT NULL,
    sub             TEXT NULL,
    com             TEXT NULL,
    tim             INTEGER NULL,
    filename        TEXT NULL,
    ext             TEXT NULL,
    fsize           INTEGER NULL,
    md5             TEXT NULL,
    w               INTEGER NULL,
    h               INTEGER NULL,
    tn_w            INTEGER NULL,
    tn_h            INTEGER NULL,
    filedeleted     INTEGER NOT NULL,
    spoiler         INTEGER NOT NULL,
    custom_spoiler  INTEGER NULL,
    replies         INTEGER NULL,
    images          INTEGER NULL,
    bumplimit       INTEGER NOT NULL,
    imagelimit      INTEGER NOT NULL,
    tag             TEXT NULL,
    semantic_url    TEXT NULL,
    since4pass      INTEGER NULL,
    unique_ips      INTEGER NULL,
    m_img           INTEGER NOT NULL,
    archived        INTEGER NOT NULL,
    archived_on     INTEGER NULL,
    board           TEXT NOT NULL
);
